# nginx-tools:template=static
# nginx-tools:type=site
server {
    listen 80;
    listen [::]:80;
    server_name {{DOMAIN}};
    root /var/www/{{DOMAIN}};
    index index.html index.htm;
    location / { try_files $uri $uri/ =404; }
}
