# nginx-tools:template=wordpress
# nginx-tools:type=site
server {
    listen 80;
    listen [::]:80;
    server_name {{DOMAIN}};
    root /var/www/{{DOMAIN}};
    index index.php;
    location / { try_files $uri $uri/ /index.php?$args; }
    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/var/run/php/php-fpm.sock;
    }
    location ~ /\.ht { deny all; }
}
